---
- include: deps.yml
- name: Copying platziverse-mqtt
  copy:
    src=platziverse-mqtt
    dest=/usr/local/src
    mode=u=rwx,g=rwx,o=rx
- name: Running npm install
  command: npm install
    chdir=/usr/local/src/platziverse-mqtt
    creates=/usr/local/src/platziverse-mqtt/node_modules
- name: Install systemd script
  copy:
    src=platziverse-mqtt.service
    dest=/lib/systemd/system
- name: Start platziverse-mqtt
  service:
    name=platziverse-mqtt
    state=restarted
    enabled=yes
