---
- hosts: backend-*
  gather_facts: False
  pre_tasks:
    - name: Install Python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup:
  roles:
    - database
    - platziverse-mqtt
    - platziverse-api
